// <auto-generated />
using Fanca_Loredana_Madalina.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fanca_Loredana_Madalina.Migrations
{
    [DbContext(typeof(Fanca_Loredana_MadalinaContext))]
    [Migration("20240116224210_InnitialMigration")]
    partial class InnitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fanca_Loredana_Madalina.Models.Candidati", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Documente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("GDPR")
                        .HasColumnType("bit");

                    b.Property<string>("Nume_Prenume")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Candidati");
                });

            modelBuilder.Entity("Fanca_Loredana_Madalina.Models.CandidatiResurseUmane", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CandidatiID")
                        .HasColumnType("int");

                    b.Property<int>("ResurseUmaneID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CandidatiID");

                    b.HasIndex("ResurseUmaneID");

                    b.ToTable("CandidatiResurseUmane");
                });

            modelBuilder.Entity("Fanca_Loredana_Madalina.Models.ResurseUmane", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Functie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Numar_Telefon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nume_Prenume")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudiiSuperioareID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StudiiSuperioareID");

                    b.ToTable("ResurseUmane");
                });

            modelBuilder.Entity("Fanca_Loredana_Madalina.Models.StudiiSuperioare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Facultate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Specializare")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("StudiiSuperioare");
                });

            modelBuilder.Entity("Fanca_Loredana_Madalina.Models.CandidatiResurseUmane", b =>
                {
                    b.HasOne("Fanca_Loredana_Madalina.Models.Candidati", "Candidati")
                        .WithMany("CandidatResursaUmane")
                        .HasForeignKey("CandidatiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fanca_Loredana_Madalina.Models.ResurseUmane", "ResurseUmane")
                        .WithMany("CandidatResursaUmane")
                        .HasForeignKey("ResurseUmaneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidati");

                    b.Navigation("ResurseUmane");
                });

            modelBuilder.Entity("Fanca_Loredana_Madalina.Models.ResurseUmane", b =>
                {
                    b.HasOne("Fanca_Loredana_Madalina.Models.StudiiSuperioare", "StudiiSuperioare")
                        .WithMany("Resurse_Umane")
                        .HasForeignKey("StudiiSuperioareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudiiSuperioare");
                });

            modelBuilder.Entity("Fanca_Loredana_Madalina.Models.Candidati", b =>
                {
                    b.Navigation("CandidatResursaUmane");
                });

            modelBuilder.Entity("Fanca_Loredana_Madalina.Models.ResurseUmane", b =>
                {
                    b.Navigation("CandidatResursaUmane");
                });

            modelBuilder.Entity("Fanca_Loredana_Madalina.Models.StudiiSuperioare", b =>
                {
                    b.Navigation("Resurse_Umane");
                });
#pragma warning restore 612, 618
        }
    }
}
